### ISSUE TITLE
First two resource links are out of date

### ISSUE THREAD

**Issue by bcfsu** [learn-co-curriculum/js-looping-and-iteration-traversing-nested-objects-readme#2]
Hi!  I tried accessing the link to Microsoft Docs on JS Recursion, and the Codeacademy lesson on recursion. The Microsoft Docs redirects to a general MDN article on how to write JS functions, and the Codeacademy resource is no longer available as of July 5, 2018.  The other two links are fine.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
